. $PSScriptRoot\close-CiscoVPN.ps1
. $PSScriptRoot\enter-CiscoVPN.ps1
. $PSScriptRoot\init.ps1
. $PSScriptRoot\new-mount.ps1
. $PSScriptRoot\new-passfile.ps1
. $PSScriptRoot\new-sesja.ps1
. $PSScriptRoot\open-xlsx.ps1
. $PSScriptRoot\save-xlsx.ps1
. $PSScriptRoot\Set-xlsx.ps1
. $PSScriptRoot\emailSMTP.ps1
. $PSScriptRoot\ImportCennik.ps1
. $PSScriptRoot\get-wmiUrz.ps1
. $PSScriptRoot\get-adminPass.ps1
. $PSScriptRoot\ping-urz.ps1
. $PSScriptRoot\restDO.ps1
